name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    container: 
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt
  run_maven:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn -v
      - run: mvn help:effective-pom